// frontend/src/app/agent/train/train.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';
import { ActivatedRoute, Params, Router } from '@angular/router';

import { CoreService } from '../../services/core.service';
import {IntentService  } from '../../services/intent.service';

import { TrainingService } from '../../services/training.service';
import { EntitiesService } from '../../services/entities.service'

@Component({
  selector: 'app-train',
  templateUrl: './train.component.html',
  styleUrls: ['./train.component.scss']
})
export class TrainComponent implements OnInit {

  selectionInfo = {
    "value":"",
    "begin":0,
    "end":0
  };

  intentId:string = null ;
  trainingData: Array<any>;
  newExampleText: String;
  newEntityName: String;

  story: any;
  entities: Array<any> = [];

  constructor(
    public storyService: IntentService,
    private _activatedRoute: ActivatedRoute,
     private _router: Router,
     private trainingService: TrainingService,
     private entitiesService: EntitiesService) {

      this.trainingData = []

      this.newEntityName = null;
  }

  ngOnInit() {
    this._activatedRoute.params.subscribe((params: Params) => {
      console.log("current intent " + params['intent_id'])
      this.intentId = params['intent_id']
      this.trainingService.getTrainingData(params['intent_id']).then(
        (result: Array<any>)=>{
          this.trainingData = result;
        }
      )

    });


    this._activatedRoute.data
      .subscribe((data:{story:any}) => {
        console.log("selected intent =>>")
        console.log(data.story)
        this.story = data.story;

    });  

    if (this.story) {
      if (this.story._id && this.story._id.$oid) {
        this.story._id = this.story._id.$oid;
      }
    }

    this.entitiesService.getEntities().then(
      (result: Array<any>) => {
        this.entities = result
      }
    )
    
  }

  // 123456
  getAnnotatedText(example){
    let text = example.text
    example.entities.forEach(entity => {
      var key =entity.value;
      var regex = new RegExp(key,'g');
      text =  text.replace(regex,'&nbsp;<mark style="background: red;">'+key+'</mark>&nbsp;' );
    });
    return text
  }
  // updateValue($event,example_index){
  //   this.trainingData[example_index]["text"]=$event.srcElement.outerText;
    
  // }

  addNewExample(){
    this.trainingData.unshift({
      "text":this.newExampleText,
      "entities":[]
    })
    this.newExampleText = "";
  }

  deleteExample(example_index){
    this.trainingData.splice(example_index,1)
  }

  deleteEntity(example_index,entity_index){
    this.trainingData[example_index].entities.splice(entity_index,1)

  }
  
  getSelectionInfo():any {
    let selection = window.getSelection(); 
    if (selection.anchorOffset == selection.extentOffset)
      return false;
      
    let result = {
      "value":selection.toString(),
    }

    if (selection.anchorOffset > selection.extentOffset)
    {
      result["begin"] = selection.extentOffset;
      result["end"] = selection.anchorOffset;
    }
    else if (selection.anchorOffset < selection.extentOffset){
      result["begin"] = selection.anchorOffset;
      result["end"] = selection.extentOffset;
    }

    return result;

  }

  addNewEntity(example_index){
    this.trainingData[example_index]["entities"].push({
      "value":this.selectionInfo.value,
      "begin":this.selectionInfo.begin,
      "end":this.selectionInfo.end,
      "name":this.newEntityName
    })
    this.newEntityName = null;
  }

  annotate(){
    // snap selection to the word
    this.snapSelectionToWord();
    let result = this.getSelectionInfo() 
    if (result)
      this.selectionInfo = result;

    console.log(this.selectionInfo);  
  }

  updateTrainingData(){
    this.trainingService.saveTrainingData(this.intentId,this.trainingData).then(()=>{
      console.log("Success");
    })
  }

  snapSelectionToWord() {
    var sel;

    // Check for existence of window.getSelection() and that it has a
    // modify() method. IE 9 has both selection APIs but no modify() method.
    if (window.getSelection && (<any>(sel = window.getSelection())).modify) {
        sel = window.getSelection();
        if (!sel.isCollapsed) {

            // Detect if selection is backwards
            var range = document.createRange();
            range.setStart(sel.anchorNode, sel.anchorOffset);
            range.setEnd(sel.focusNode, sel.focusOffset);
            var backwards = range.collapsed;
            range.detach();

            // modify() works on the focus of the selection
            var endNode = sel.focusNode, endOffset = sel.focusOffset;
            sel.collapse(sel.anchorNode, sel.anchorOffset);

            var direction = [];
            if (backwards) {
                direction = ['backward', 'forward'];
            } else {
                direction = ['forward', 'backward'];
            }

            sel.modify("move", direction[0], "character");
            sel.modify("move", direction[1], "word");
            sel.extend(endNode, endOffset);
            sel.modify("extend", direction[1], "character");
            sel.modify("extend", direction[0], "word");
        }
    } else if ( (sel = (<any>document).selection) && sel.type != "Control") {
        var textRange = sel.createRange();
        if (textRange.text) {
            textRange.expand("word");
            // Move the end back to not include the word's trailing space(s),
            // if necessary
            while (/\s$/.test(textRange.text)) {
                textRange.moveEnd("character", -1);
            }
            textRange.select();
        }
    }
}

//place curser at the end of content editable div
  placeCaretAtEnd(el) {
    el.focus();
    if (typeof window.getSelection != "undefined"
            && typeof document.createRange != "undefined") {
        var range = document.createRange();
        range.selectNodeContents(el);
        range.collapse(false);
        var sel = window.getSelection();
        sel.removeAllRanges();
        sel.addRange(range);
    } else if (typeof document.body.createTextRange != "undefined") {
        var textRange = document.body.createTextRange();
        textRange.moveToElementText(el);
        textRange.collapse(false);
        textRange.select();
    }
  }

}

<div class="header" >
  <div fxLayout="row" fxLayoutAlign="space-between center"  >
      <h2 fxFlex="90">Train your intent</h2>
      <div>
          <button mat-raised-button (click)="updateTrainingData()" color="primary">Save Training Data </button>
      </div>
      
  </div>
  <p fxFlex="85">
      Train your story for possible user inputs. Tag required parameters using mouse and give em labels  
    </p>

</div>

<mat-card >
  <mat-form-field class="full-width">
    <textarea matInput [(ngModel)]="newExampleText" placeholder="enter example text here"></textarea>
  </mat-form-field>
  <button mat-raised-button color="accent" (click)="addNewExample()">Add to training set</button>
</mat-card >

<div class="mat-accordion">
<mat-accordion>
  <mat-expansion-panel *ngFor="let example of trainingData;let example_index = index" [expanded]="example_index == 0" (opened)="selectionInfo.value = ''">
    <mat-expansion-panel-header>
      <mat-panel-title [innerHTML]="getAnnotatedText(example)">
      </mat-panel-title>
    </mat-expansion-panel-header>

    <div fxLayout="row">
      <div fxFlex="90" id="textarea_highlight" contenteditable="true" role="textarea" (mouseup)="annotate()" appAutofocus  (blur)="example.text = $event.target.outerText;">{{example.text}}</div>
      <button mat-icon-button fxFlex="10">
        <mat-icon aria-label="Delete this example" (click)="deleteExample(example_index)">delete</mat-icon>
      </button>

    </div>

    <div class="add-entity">
        <span *ngIf="this.selectionInfo.value == ''; else elseBlock" class="round-button"> Select text to add an entity </span>

        <ng-template #elseBlock>
          <mat-form-field>
              <input matInput type="text" [(ngModel)]="newEntityName" placeholder="entity name" aria-label="entity" [matAutocomplete]="auto" appAutofocus>
              <mat-autocomplete #auto="matAutocomplete">
                  <mat-option *ngFor="let entity of entities" [value]="entity.name">
                    <span>{{ entity.name }}</span>
                  </mat-option>
                </mat-autocomplete>
          </mat-form-field>

            

          <span class="round-button" (click)="newEntityName && addNewEntity(example_index)"> Add an entity for
            <b>"{{this.selectionInfo.value}}"</b>
          </span>
        </ng-template>
      </div>
      
    <div class="entity-table">

      <table width="100%">
        <h3>Entities</h3>
        <tr class="table-header">
          <td>Entity</td>
          <td>Value</td>
          <td></td>
        </tr>
        <tr *ngFor="let entity of example.entities;let entity_index = index">
          <td>{{entity.name}}</td>
          <td>{{entity.value}}</td>
          <td>
            <button mat-icon-button (click)="deleteEntity(example_index,entity_index)" >
              <mat-icon aria-label="Delete this entity" >close</mat-icon>
            </button>
          </td>
        </tr>
      </table>
    </div>
  </mat-expansion-panel>
</mat-accordion>
</div>

// frontend/app/admin/intents/[id]/train/page.tsx
"use client";

import React, { useState, useEffect } from 'react';
import { getIntent } from '../../../../services/intents';
import { getTrainingData, saveTrainingData,EntityModel, IntentModel } from '../../../../services/training';
import { getEntities } from '../../../../services/entities';
import { useSnackbar } from '../../../../components/Snackbar/SnackbarContext';
import './style.css';

interface Entity {
  name: string;
  value: string;
  begin: number;
  end: number;
}

interface Example {
  text: string;
  entities: Entity[];
}

interface SelectionInfo {
  value: string;
  begin: number;
  end: number;
}

type PageProps = {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}

export default function TrainPage({ params }: PageProps) {
  const { id } = React.use(params);
  const { addSnackbar } = useSnackbar();
  const [trainingData, setTrainingData] = useState<Example[]>([]);
  const [newExampleText, setNewExampleText] = useState('');
  const [newEntityName, setNewEntityName] = useState('');
  const [entities, setEntities] = useState<EntityModel[]>([]);
  const [intent, setIntent] = useState<IntentModel>({ name: '', parameters: [], speechResponse: '', apiTrigger: false });
  const [selectionInfo, setSelectionInfo] = useState<SelectionInfo>({
    value: '',
    begin: 0,
    end: 0
  });

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [intentData, trainingDataResult, entitiesData] = await Promise.all([
          getIntent(id),
          getTrainingData(id),
          getEntities()
        ]);
        setIntent(intentData);
        setTrainingData(trainingDataResult);
        setEntities(entitiesData);
      } catch (error) {
        console.error('Error fetching data:', error);
        addSnackbar('Failed to load training data', 'error');
      }
    };
    fetchData();
  }, [id, addSnackbar]);

  const getAnnotatedText = (example: Example) => {
    let text = example.text;
    example.entities.forEach(entity => {
      const key = entity.value;
      text = text.replace(
        new RegExp(key, 'g'),
        `<mark class="entity-highlight">${key}</mark>`
      );
    });
    return text;
  };

  const addNewExample = () => {
    if (!newExampleText.trim()) return;
    setTrainingData(prev => [{
      text: newExampleText,
      entities: []
    }, ...prev]);
    setNewExampleText('');
  };

  const deleteExample = (exampleIndex: number) => {
    setTrainingData(prev => prev.filter((_, index) => index !== exampleIndex));
  };

  const deleteEntity = (exampleIndex: number, entityIndex: number) => {
    setTrainingData(prev => prev.map((example, index) => {
      if (index === exampleIndex) {
        return {
          ...example,
          entities: example.entities.filter((_, eIndex) => eIndex !== entityIndex)
        };
      }
      return example;
    }));
  };

  const snapSelectionToWord = () => {
    const sel = window.getSelection();
    if (!sel || sel.isCollapsed) return;

    const range = document.createRange();
    range.setStart(sel.anchorNode!, sel.anchorOffset);
    range.setEnd(sel.focusNode!, sel.focusOffset);
    const backwards = range.collapsed;
    range.detach();

    const endNode = sel.focusNode;
    const endOffset = sel.focusOffset;
    sel.collapse(sel.anchorNode, sel.anchorOffset);

    const direction = backwards ? ['backward', 'forward'] : ['forward', 'backward'];
    sel.modify("move", direction[0], "character");
    sel.modify("move", direction[1], "word");
    sel.extend(endNode!, endOffset);
    sel.modify("extend", direction[1], "character");
    sel.modify("extend", direction[0], "word");
  };

  const getSelectionInfo = (): SelectionInfo | null => {
    const selection = window.getSelection();
    if (!selection || selection.anchorOffset === selection.focusOffset) return null;

    const value = selection.toString();
    const begin = Math.min(selection.anchorOffset, selection.focusOffset);
    const end = Math.max(selection.anchorOffset, selection.focusOffset);

    return { value, begin, end };
  };

  const handleAnnotate = () => {
    snapSelectionToWord();
    const info = getSelectionInfo();
    if (info) {
      setSelectionInfo(info);
    }
  };

  const addNewEntity = (exampleIndex: number) => {
    if (!newEntityName || !selectionInfo.value) return;

    setTrainingData(prev => prev.map((example, index) => {
      if (index === exampleIndex) {
        return {
          ...example,
          entities: [...example.entities, {
            value: selectionInfo.value,
            begin: selectionInfo.begin,
            end: selectionInfo.end,
            name: newEntityName
          }]
        };
      }
      return example;
    }));
    setNewEntityName('');
    setSelectionInfo({ value: '', begin: 0, end: 0 });
  };

  const updateTrainingData = async () => {
    try {
      await saveTrainingData(id, trainingData);
      addSnackbar('Training data saved successfully', 'success');
    } catch (error) {
      console.error('Error saving training data:', error);
      addSnackbar('Failed to save training data', 'error');
    }
  };

  return (
    <div className="p-6 max-w-7xl mx-auto">
      <div className="mb-8">
        <div className="flex justify-between items-center">
          <h1 className="text-2xl font-semibold text-gray-800">Train Intent: {intent?.name}</h1>
          <button
            onClick={updateTrainingData}
            className="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors duration-200"
          >
            Save Training Data
          </button>
        </div>
        <p className="text-gray-600 mt-1">
          Train your intent for possible user inputs. Tag required parameters using mouse and give them labels.
        </p>
      </div>

      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-6">
        <div className="flex gap-4">
          <input
            type="text"
            value={newExampleText}
            onChange={(e) => setNewExampleText(e.target.value)}
            placeholder="Enter example text here"
            className="flex-1 p-2.5 rounded-lg border border-gray-300 focus:ring-2 focus:ring-green-200 focus:border-green-500"
          />
          <button
            onClick={addNewExample}
            className="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors duration-200"
          >
            Add to training set
          </button>
        </div>
      </div>

      <div className="space-y-4">
        {trainingData.map((example, exampleIndex) => (
          <div key={exampleIndex} className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex justify-between items-start mb-4">
              <div
                className="flex-1 p-4 bg-gray-50 rounded-lg"
                dangerouslySetInnerHTML={{ __html: getAnnotatedText(example) }}
              />
              <button
                onClick={() => deleteExample(exampleIndex)}
                className="ml-2 p-2 text-red-500 hover:bg-red-50 rounded-lg"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            <div
              className="p-4 bg-gray-50 rounded-lg mb-4"
              contentEditable
              onMouseUp={handleAnnotate}
              suppressContentEditableWarning
            >
              {example.text}
            </div>

            <div className="mb-4">
              {selectionInfo.value && (
                <div className="flex gap-4 items-center">
                  <select
                    value={newEntityName}
                    onChange={(e) => setNewEntityName(e.target.value)}
                    className="p-2 border border-gray-300 rounded-lg"
                  >
                    <option value="">Select entity</option>
                    {entities.map((entity, index) => (
                      <option key={index} value={entity.name}>
                        {entity.name}
                      </option>
                    ))}
                  </select>
                  <button
                    onClick={() => addNewEntity(exampleIndex)}
                    className="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors duration-200"
                  >
                    Add Entity
                  </button>
                </div>
              )}

              {example.entities.length > 0 && (
                <div className="mt-4">
                  <h4 className="font-medium text-gray-700 mb-2">Tagged Entities:</h4>
                  <div className="space-y-2">
                    {example.entities.map((entity, entityIndex) => (
                      <div key={entityIndex} className="flex items-center gap-2">
                        <span className="px-2 py-1 bg-green-100 text-green-800 rounded">
                          {entity.name}: {entity.value}
                        </span>
                        <button
                          onClick={() => deleteEntity(exampleIndex, entityIndex)}
                          className="p-1 text-red-500 hover:bg-red-50 rounded"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
